version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.simple-kbs
    image: simple-kbs-server:latest
    restart: always
    environment:
      KBS_DB_TYPE: mysql
      KBS_DB_HOST: db
      KBS_DB_USER: kbsuser
      KBS_DB_PW: kbspassword
      KBS_DB: simple_kbs
      RUST_LOG: info
    ports:
      - "44444:44444"
    depends_on:
      - db
    volumes:
      - .:/usr/src/simple-kbs
    working_dir: /usr/src/simple-kbs

  cli:
    depends_on:
      - server
    entrypoint: bash
    image: simple-kbs-server:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/simple-kbs
    working_dir: /usr/src/simple-kbs

  db:
    build:
      context: .
      dockerfile: Dockerfile.kbs-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: unused
      MARIADB_DATABASE: simple_kbs
      MARIADB_USER: kbsuser
      MARIADB_PASSWORD: kbspassword
